name = "NubTechCMP1"
author = "Scorpio"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6391ae55f0baa81e2e0330187e8646c34d0eef8e7c1fc662d709a9bf526ef1f"

[versions]
fabric = "0.19.1"
minecraft = "1.20.4"
