name = "NubTechCMP1"
author = "Scorpio"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a3dd0921ee905aa59a8dcfb0f6750cf66d2275bccbb6db38c11a02a94c6600e"

[versions]
fabric = "0.19.1"
minecraft = "1.20.4"
