name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58d608981ea33062dc3fe37166aa0a90de00c4ef37828ecf7de7c3e0dc42559a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
