name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d04fedab2235136121a6b7037d4b78c7ec2689a56cb855a162fd52f27e9de47"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
