name = "RedstoneToolkit"
author = "Scorpio"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41434762213fb2c93ef22d39e25c957df9e33a44b0a48ea7832882a22c0b8e1b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
